local DefRX= require "DefUtil.DefRX.DefRX"
go.property("target", hash(""))
function set_position(self, message_id, message, sender)
	if message.id == self.target then
		go.set_position(go.get_world_position(self.target))
		msg.post("#trail_maker", "update")
	end
end

function init(self)
	DefRX.create_stream("target_update")
	DefRX.observe(self, "target_update", set_position)
	
end

function on_message(self, message_id, message, sender)
	DefRX.on_message(self, message_id, message, sender)
end