local DefUI= require "DefUtil.DefUI.DefUI"
local UI = require "assets.ui.title.title"
local PROXY = msg.url("main:/scene_proxy")
function start(self,action_id,action,button)
	msg.post(PROXY, "change_scene",{next="#ingame"})
end

function init(self)
	DefUI.init(self)
	UI.init(self)
	DefUI.create_button(self, "start", self.node["start"], {pressed = start})
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	DefUI.on_input(self, action_id, action)
end