go.property("combo", 0)
function init(self)
	label.set_text("#label", tostring(self.combo).." COMBO!")
	go.animate("#label", "outline.w", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_INCUBIC, 0.7)
	go.animate("#label", "color.w", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_INCUBIC, 0.7)
	go.animate(".", "position.y", go.PLAYBACK_ONCE_FORWARD, go.get_position().y+300, go.EASING_INCUBIC, 0.7,0,function()
		go.delete()
	end)
end
